# Generated by Django 5.2.8 on 2025-11-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_s', models.PositiveIntegerField(default=20)),
                ('model_name', models.CharField(default='facebook/musicgen-small', max_length=100)),
                ('temperature', models.FloatField(default=1.0)),
                ('top_k', models.IntegerField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('guidance_scale', models.FloatField(default=3.0)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='generated_music/')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='musicgen.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_moods', models.JSONField(default=list)),
                ('multi_moods', models.JSONField(default=list)),
                ('sentiment_label', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('spotify_tracks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='musicgen.prompt')),
            ],
        ),
    ]
